insert into clubes (nome,valor) values
("Atlético Goianiense",1),
("Atlético Mineiro",1),
("Atlético Paranaense",1),
("Avaí",1),
("Bahia",1),
("Botafogo",1),
("Chapecoense",1),
("Corinthians",1),
("Coritiba",1),
("Cruzeiro",1),
("Flamengo",1),
("Fluminense",1),
("Grêmio",1),
("Palmeiras",1),
("Ponte Preta",1),
("Santos",1),
("São Paulo",1),
("Sport",1),
("Vasco da Gama",1),
("Vitória",1);